#:set RADIUS dp(25)





<Background@Widget>:
    bg_color: []
    canvas.before:
        Color:
            rgba: self.bg_color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [RADIUS]





<ChoiceSp@Spinner+BaseMixin>:
    font_name: "UI"
    bold: True
    italic: True
    background_color: 0,0,0,0
    background_normal: ""
    background_down: ""
    canvas.before:
        Color:
            rgba: app.colors["primary"]
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [self.height/2]



