<Button_1@Button+BaseMixin+FloatLayout>:
    img: ""
    normal_color: []
    down_color: []
    font_name: "UI"
    bold: True
    italic: True
    background_normal: ""
    background_down: ""
    background_color: 0,0,0,0
    font_size: sp(app.font_sizes["subtitle"])
    radius: [self.height/2, self.height/2, self.height/2, self.height/2]
    canvas.before:
        Color:
            rgba: app.colors['shadow']
        RoundedRectangle:
            pos: self.x, self.y - (dp(4) if self.state == 'normal' else 0)
            size: self.size
            radius: [self.height/2]
        Color:
            rgba: app.colors['highlight'] if self.state == 'normal' else (0,0,0,0)
        RoundedRectangle:
            pos: self.x, self.y + self.height * 0.1
            size: self.width, self.height * 0.8
            radius: [self.height/2]
        Color:
            rgba: self.normal_color if self.state == "normal" else self.down_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [self.height/2]
        Color:
            rgba: app.colors['stroke']
        Line:
            rounded_rectangle: (self.x, self.y, self.width, self.height, self.height/2, self.height/2, self.height/2, self.height/2)
            width: dp(1)
        Color:
            rgba: 1,1,1, .08 if self.state=="normal" else 0
        RoundedRectangle:
            pos: self.x, self.y + self.height*0.4
            size: self.width, self.height*0.6
            radius: [self.height/2]

<Button_1>:
    normal_color: app.colors['primary']
    down_color: app.colors['primary_dark']
    color: app.colors['on_primary']
    LabelImg:
        id: label_img
        color: root.color
        text: root.img
        font_size: app.font_sizes["emoji"]

