<LabelImg@BaseMixin+Label>:
    font_name: "MDI"
    size_hint: 0.2, 1
    color:  app.colors["on_surface"]
    pos_hint: {"center_y": .5, "center_x": .1}
    halign: "center"
    valign: "center"


<LabelTxt@BaseMixin+Label>:
    font_name: "UI"
    bold: True
    size_hint: 0.8, 1
    color: app.colors["on_surface"]
    halign: "center"
    valign: "middle"
    pos_hint: {"center_y": .5, "center_x": .6}
