#:kivy 2.3.1

#:import dp kivy.metrics.dp
<Title@FloatLayout>:
    text: ""
    img: ""

<Title>

    Background:
        pos_hint: {"center_y": .5, "center_x": .5}
        size_hint_x: 1.1
        bg_color: app.colors["surface"]
    LabelImg:
        font_size:sp(app.font_sizes["emoji"])
        text: root.img

    LabelTxt:
        text: root.text
        text_align: "center"
        #text_size: self.size
        font_size:sp(app.font_sizes["title"])

