#:kivy 2.3.0
#:import Factory kivy.factory.Factory
#:import dp kivy.metrics.dp



<SettingsScreen>:
    name: "settings"
    orientation: "vertical"
    spacing: self.height/40
    padding: self.width/20
    Title:
        text: root.text_title
        img: root.img_title
    Button_1:
        id: go_main
        text: root.text_back
        img: root.img_back
        on_release:app.root.current = "main"

    Button_1:
        id: ddl_open
        text: "Русский" if app.config.get_param("app","language") == "ru" else "English"
        on_release:
            (hasattr(self, "dropdown") or setattr(self, "dropdown", Factory.DrDown()))
            self.dropdown.open(self)
    Widget:
    Button_1:
        id: ddt_open
    Widget:
        size_hint: 1, 1


    Label:
        text: root.text_version
        font_size: "12sp"
        color:  app.colors["accent"]
        height: self.texture_size[1] + 10